### ISSUE TITLE
しぃペインターがCheepJ 2.1で起動しない

### ISSUE THREAD

**Issue by sakots** [satopian/POTI-board_ChickenPaint#3]
略/latest/略 でリンクしていると、いつまでも起動待機画面から進まないようです。

https://twitter.com/Tagayashiichiro/status/1400158740167360512

**Comment by satopian** [comment]
latstと2.1
どちらもファイルの中身は同じ(diffチェック済み)。
こちらで試した限りでは｢Edge｣起動しない。
｢Chrome｣と｢Firefox｣は起動する。
Edgeの挙動がいろいろ変(Chromiumなのに?←いまここ)
https://github.com/leaningtech/cheerpj-appletrunner/issues
↑
解決するかどうかわかりませんが、CheerpJのサポート。
ここで嘆願しても最終的にどの環境でも動かなくなってしまったら、しぃぺを外して使ってもらうしかないですね…。

**Comment by satopian** [comment]
https://github.com/leaningtech/cheerpj-appletrunner/issues/46
Chromeでは起動…と思いましたが、起動しませんでした。Chrome拡張機能が動いていました。
開発元に問い合わせましたが、修正されるかどうかはなんとも…。

**Comment by satopian** [comment]
@sakots 
サポートからの回答。
```
Using "latest" is not safe as it can serve a mix of what you, the CDN and the browser have cached to that address.
Please use the official releases of the runtime (like the 20200206 that you linked or the latest release version 2.2).

As a matter of fact, starting from the last release, the latest endpoint won't be update anymore.

I've tested the applet with the latest release https://cjrtnc.leaningtech.com/2.2/loader.js and everything seems to be working.
```
"latest"は使用してはいけない。使うなら、
最新版の
https://cjrtnc.leaningtech.com/2.2/loader.js
または安定版の
 https://cjrtnc.leaningtech.com/20200206/loader.js
2.2で動作確認して動くようならそちらに貼り替えます。

**Comment by sakots** [comment]
https://cjrtnc.leaningtech.com/2.2/loader.js
以下2.2での起動が確認できました。

- Edge バージョン 91.0.864.41 (x64)
- Firefox 88.0.1 (x64)
- chrome 91.0.4460.0（Developer Build）(x64)

細かい動作確認はできていませんが、問題なさそうです。

**Comment by satopian** [comment]
管理しているテンプレートのurlを2.2に入れ替えました。

**Comment by sakots** [comment]
お手数おかけします。

**Comment by satopian** [comment]
`sN.src = "<% def(cheerpj_url)%><% echo(cheerpj_url)%><% elsedef %>https://cjrtnc.leaningtech.com/2.2/loader.js<% /def %>";`
テーマのHTMLのCheerpJの起動urlを変数化しました。
potiboard.phpでurlを管理します。
変更が必要になったらpotiboard.phpを上書きアップデート。
